function handleMoviesClick() {
    console.log('handleMoviesClick - For backward compatibility with hard-coded buttons');
    
    /* Find the movies button generated by the API */
    const movieButton = document.querySelector('button[id="70"]'); // Movies ID from API
    
    /* If found, simulate a click on it to use the API-driven implementation */
    if (movieButton) {
        movieButton.click();
    } else {
        /* Fallback for cases where the API button isn't found */
        previous_page = current_page;
        current_page = 'movies';
        
        /* Same sequence as in API click handler */
        enableBackKeyForwarding();
        setMoviesKeys();
        openMovies('Activate');
    }
}

function handleRadioClick() {
    console.log('Opening Radio...');
    
    // Hide default view
    //document.querySelector('.default-view').style.display = 'none';
    
    // Hide entertainment view
    document.querySelector('#entertainment_menu').style.display = 'none';
    
    // Keep sidebar visible
    const sidebar = document.querySelector('.sidebar');
    if (sidebar) {
        sidebar.style.display = 'none';
    }
    
    // Show radio view
    const radioView = document.querySelector('.radio-view');
    if (radioView) {
        radioView.style.display = 'flex';
        //radioView.style.marginLeft = '15%'; // Align with sidebar
    }

    // First make sure to remove any radio channels from the TV app
    if (typeof removeRadioChannelsFromTV === 'function') {
        removeRadioChannelsFromTV();
    }

    // Initialize radio channels
    openRadio();
}

// Add handler for radio channel clicks
// function handleRadioChannelClick(channelNumber) {
//     console.log('Opening Radio Channel:', channelNumber);
    
//     // // Clear active state from all radio cards
//     // document.querySelectorAll('.radio-card').forEach(card => {
//     //     card.classList.remove('active');
//     // });
    
//     // // Add active state to clicked card
//     // const clickedCard = document.querySelector(`.radio-card[data-type="radio${channelNumber}"]`);
//     // if (clickedCard) {
//     //     clickedCard.classList.add('active');
//     // }

//     // Use existing radio channel selection function
//     selectRadioChannel(channelNumber);
// }

function handleEntertainmentClick() {
    console.log('Opening Entertainment...');

    //setting previous and current page
    previous_page = current_page;
    current_page = "entertainment_menu";

    document.getElementById(previous_page).style.display = 'none';
    document.getElementById(current_page).style.display = 'flex';

    //document.getElementById("tv_button").focus();

}


// Add entertainment casting handler
function handleCastingClick() {
    console.log('handleCastingClick - For backward compatibility with hard-coded buttons');
    
    /* Find the casting button generated by the API */
    const castingButton = document.querySelector('button[id="98"]'); // Casting ID from API
    
    /* If found, simulate a click on it to use the API-driven implementation */
    if (castingButton) {
        castingButton.click();
    } else {
        /* Fallback for cases where the API button isn't found */
        previous_page = current_page;
        current_page = 'casting';
        
        /* Same sequence as in API click handler */
        enableBackKeyForwarding();
        SelectCast('Activate');
    }
}

/**
 * This function enters the Movies module from API menu
 * @param {string} action - 'Activate' or 'Deactivate'
 */
// function openMovies(action) {
//     console.log('openMovies called with action:', action);
//     
//     if (action === 'Activate') {
//         // Display movies view
//         document.getElementById('movies').style.display = 'flex';
//         
//         // Deactivate dashboard
//         changeCDBstate('Deactivate');
//     } else if (action === 'Deactivate') {
//         // Hide movies view
//         document.getElementById('movies').style.display = 'none';
//         
//         // Reset controls
//         setRcControlSelective();
//     }
// }

/**
 * This function enters the Casting module from API menu
 * @param {string} action - 'Activate' or 'Deactivate'
 */
// function openCasting(action) {
//     console.log('openCasting called with action:', action);
//     
//     // Redirect to the legacy function to maintain compatibility
//     SelectCast(action);
// } 