/* Browser-only adapter for the original PES Footscray layout. No hospital APIs. */
'use strict';
const $ = (selector) => document.querySelector(selector);
const dialog = $('#demo-dialog');
const content = $('#demo-content');
const sections = ['default_view','entertainment_menu','hospitalinfo_menu','mycare_menu','clinicalservices_menu'];
const historyStack = [];
let current = 'default_view';
let cleanup = () => {};
let toastTimer;
let clockTimer;
const menuTargets = ['entertainment_menu','hospitalinfo_menu','mycare_menu','clinicalservices_menu'];
function showSection(target, remember = true) {
  closeDialog();
  if (remember && current !== target) historyStack.push(current);
  current = target;
  sections.forEach(id => { document.getElementById(id).style.display = id === target ? 'flex' : 'none'; });
  document.querySelectorAll('.menu-item').forEach((button,i) => {
    if(menuTargets[i] === target) button.setAttribute('aria-current','page');
    else button.removeAttribute('aria-current');
  });
  $('#demo-back').disabled = historyStack.length === 0;
}
function closeDialog(){cleanup();cleanup=()=>{};clearInterval(clockTimer);if(dialog.open)dialog.close();}
function openDialog(title, html) {
  closeDialog();
  $('#demo-dialog-title').textContent = title;
  content.innerHTML = html;
  dialog.showModal();
}
function toast(message){$('#demo-status').textContent=message;$('#demo-status').style.display='block';clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#demo-status').style.display='none',3500);}
function sampleNote(text='This is a simulated portfolio interaction. No hospital system is connected.') {return `<p class="demo-note">${text}</p>`;}
function about(){openDialog('About this project',`<p><strong>PES Footscray</strong> is a patient entertainment interface. This browser demo adapts the original hospital TV dashboard so you can explore it on a laptop or phone.</p><p>Built by <strong>Ryan Pathirana</strong>. The original project includes JavaScript menu navigation, API-driven content, media interfaces and JAPIT/WIXP TV integration.</p><div class="demo-about"><span>JavaScript</span><span>HTML & CSS</span><span>Responsive UI</span><span>Keyboard navigation</span><span>TV integration</span></div><p>Try the four menus, select a sample channel, test the casting flow, complete a sample survey, or use the discharge checklist.</p>${sampleNote('TV tuning, radio, casting and HDMI are simulations. The animated previews and audio tones are generated locally. Survey responses stay in this page and are discarded when closed. This is not an official hospital website.')}<p><strong>Controls:</strong> click or tap to select; use Tab or arrow keys to move; Enter to activate; Escape to close. Home returns to the welcome screen.</p>`);}
function animationPreview(title, mode='TV') {
  openDialog(title,`${sampleNote('Simulated '+mode+' player • original sample animation, generated in your browser. No live broadcast.')}<div class="demo-options" id="channel-options"></div><div class="demo-screen"><canvas id="sample-canvas" width="800" height="450" aria-label="Sample animated landscape"></canvas><div class="screen-label"><b id="sample-title"></b><br>LOCAL ANIMATION · DEMO</div></div><div><button id="sample-pause">Pause preview</button><button id="sample-fullscreen">Full screen</button></div>`);
  const names=mode==='TV'?['Channel 1 · Nature','Channel 2 · Horizons','Channel 3 · Night sky']:['Quiet landscape','Ocean colours','Evening lights'];
  let choice=0,paused=false,frame,time=0;
  const canvas=$('#sample-canvas'),ctx=canvas.getContext('2d');
  const buttons=names.map((name,index)=>{const button=document.createElement('button');button.textContent=name;button.setAttribute('aria-pressed',String(index===0));button.onclick=()=>{choice=index;$('#sample-title').textContent=name;buttons.forEach((b,i)=>b.setAttribute('aria-pressed',String(i===index)));};$('#channel-options').append(button);return button;});
  $('#sample-title').textContent=names[0];
  const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
  function draw(){if(!paused&&!reduced)time+=0.007;const palettes=[['#153762','#71a9b4','#254a5c'],['#275880','#bacdda','#527e99'],['#101831','#4a4e8c','#222d54']];const p=palettes[choice];const gradient=ctx.createLinearGradient(0,0,0,450);gradient.addColorStop(0,p[0]);gradient.addColorStop(1,p[1]);ctx.fillStyle=gradient;ctx.fillRect(0,0,800,450);ctx.fillStyle=choice===2?'#e8ecfa':'#f9dda6';ctx.beginPath();ctx.arc(590,115,42,0,Math.PI*2);ctx.fill();for(let layer=0;layer<4;layer++){ctx.fillStyle=p[2];ctx.globalAlpha=.35+layer*.18;ctx.beginPath();ctx.moveTo(0,450);for(let x=0;x<=800;x+=5)ctx.lineTo(x,235+layer*45+Math.sin(x/110+time+layer)*28+Math.cos(x/63+layer)*15);ctx.lineTo(800,450);ctx.fill();}ctx.globalAlpha=1;frame=requestAnimationFrame(draw);}
  draw();$('#sample-pause').onclick=()=>{paused=!paused;$('#sample-pause').textContent=paused?'Play preview':'Pause preview';};
  $('#sample-fullscreen').onclick=async()=>{try{if(canvas.requestFullscreen)await canvas.requestFullscreen();else toast('Full screen is not available in this browser.');}catch{toast('Full screen is not available in this browser.');}};
  cleanup=()=>cancelAnimationFrame(frame);
}
function radio(){openDialog('Radio preview',`${sampleNote('Sample audio tones only — these are not live radio stations. Playback starts only when you press Play.')}<div class="demo-options"><button data-tone="220" aria-pressed="true">Calm</button><button data-tone="293.66" aria-pressed="false">Focus</button><button data-tone="349.23" aria-pressed="false">Evening</button></div><div class="demo-screen"><div><h3 id="tone-label">Calm</h3><p style="color:#b9d9e9">LOCAL AUDIO PREVIEW</p><button id="tone-play">Play sample</button></div></div><p><label>Volume <input id="tone-volume" type="range" min="0" max="0.15" step="0.01" value="0.04"></label></p>`);
  let audio,osc,gain,frequency=220,playing=false;
  $('#tone-play').onclick=async()=>{if(playing){await audio.suspend();playing=false;$('#tone-play').textContent='Play sample';return;}const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio){toast('Audio preview is not supported in this browser.');return;}try{if(!audio){audio=new Audio();osc=audio.createOscillator();gain=audio.createGain();osc.type='sine';osc.frequency.value=frequency;gain.gain.value=Number($('#tone-volume').value);osc.connect(gain);gain.connect(audio.destination);osc.start();}await audio.resume();playing=true;$('#tone-play').textContent='Pause sample';}catch{toast('Audio could not start. Please try again.');}};
  content.querySelectorAll('[data-tone]').forEach(b=>b.onclick=()=>{frequency=Number(b.dataset.tone);if(osc)osc.frequency.setTargetAtTime(frequency,audio.currentTime,.1);$('#tone-label').textContent=b.textContent;content.querySelectorAll('[data-tone]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));});
  $('#tone-volume').oninput=e=>{if(gain)gain.gain.value=Number(e.target.value);};cleanup=()=>{if(audio)audio.close().catch(()=>{});};
}
function casting(){openDialog('Casting',`${sampleNote()}<p>Walk through the bedside screen pairing experience.</p><ol><li>Choose a nearby screen.</li><li>Enter the pairing code on your device.</li><li>Confirm the connection.</li></ol><div class="demo-screen"><div><p style="color:#c0d9e9">DEMO SCREEN 01</p><h3 style="font-size:40px;letter-spacing:8px">482 716</h3><span id="cast-state">Ready to pair</span></div></div><button id="cast-pair">Simulate pairing</button>`);$('#cast-pair').onclick=()=>{$('#cast-state').textContent='Demo device connected';$('#cast-pair').textContent='Disconnect';$('#cast-pair').onclick=casting;};}
function checklist(){openDialog('Management and discharge',`${sampleNote('Sample checklist for demonstrating the interface, not medical instructions. Changes remain in this open panel only.')}<p>Try marking the example steps as complete.</p><div class="demo-checklist"><label><input type="checkbox"> Review sample discharge summary</label><label><input type="checkbox"> View example follow-up details</label><label><input type="checkbox"> Confirm a sample transport plan</label></div><progress class="demo-progress" max="3" value="0"></progress><p id="check-progress" role="status">0 of 3 demo steps completed</p>`);content.querySelectorAll('input').forEach(x=>x.onchange=()=>{const count=content.querySelectorAll('input:checked').length;$('.demo-progress').value=count;$('#check-progress').textContent=`${count} of 3 demo steps completed`;});}
function survey(title){openDialog(title,`${sampleNote('Practice form only. No patient information is collected or sent.')}<form class="demo-form"><label>How easy was the demo to navigate?<select required name="rating"><option value="">Choose a response</option><option>Very easy</option><option>Easy</option><option>Could be easier</option></select></label><label>Which section did you explore?<select required name="section"><option value="">Choose a section</option><option>Entertainment</option><option>Hospital Info</option><option>My Care</option><option>Clinical Services</option></select></label><button type="submit">Submit sample response</button></form>`);$('.demo-form').onsubmit=e=>{e.preventDefault();content.innerHTML='<div class="demo-result" role="status"><strong>Sample survey completed.</strong><p>Thanks for trying the interaction. Nothing was sent or saved.</p></div><button id="survey-again">Try again</button>';$('#survey-again').onclick=()=>survey(title);};}
function info(title,text){openDialog(title,`${sampleNote('Example information page for this portfolio demo. Consult the hospital’s official information for real services.')}<p>${text}</p>`);}
function sharing(){openDialog('Clinical sharing',`${sampleNote('HDMI input switching is simulated. A normal web browser cannot control a hospital TV input.')}<div class="demo-screen"><div><h3 id="hdmi-state">HDMI 1 · Standby</h3><p style="color:#c0d9e9">Sample connected-device workflow</p></div></div><button id="hdmi-toggle">Connect demo device</button>`);let connected=false;$('#hdmi-toggle').onclick=()=>{connected=!connected;$('#hdmi-state').textContent=connected?'HDMI 1 · Demo screen sharing':'HDMI 1 · Standby';$('#hdmi-toggle').textContent=connected?'Disconnect demo device':'Connect demo device';};}
function clock(){openDialog('Melbourne time','<div class="demo-clock" id="large-clock"></div><p style="text-align:center">Australia / Melbourne</p>');const tick=()=>$('#large-clock').textContent=new Intl.DateTimeFormat('en-AU',{timeZone:'Australia/Melbourne',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(new Date());tick();clockTimer=setInterval(tick,1000);}
const actions={television:()=>animationPreview('Television','TV'),casting,movies:()=>animationPreview('Movies','movie'),radio,'management-and-discharge-button':checklist,'blacktown-surveys':()=>survey('Sample experience survey'),'carers-surveys':()=>survey('Carers survey'),'patient-survey':()=>survey('Patient survey'),'clinical-sharing':sharing,time:clock,information:()=>info('Clinical information','This panel demonstrates how service information can be presented on a bedside screen. The production interface can launch connected clinical applications; this demo displays sample content only.'),welcome:()=>info('Welcome','Welcome to the PES Footscray portfolio demo. Explore the menus to see how a bedside entertainment interface brings information and activities together. Use the Back and Home controls to move around.'),visiting:()=>info('Visiting hours','An information panel can show visitor guidance and display a document from a hospital content system. This public demo uses example content and does not publish current visiting hours.'),rights:()=>info('Healthcare rights','This is a sample document-style view. In a hospital installation, this menu opens the organisation’s approved patient information. The public demo contains no clinical or patient records.'),reach:()=>info('Reach','This menu demonstrates an information page for a patient support programme. No care request or notification can be sent from this demo.')};
document.querySelectorAll('.menu-item').forEach((button,index)=>{button.onclick=()=>showSection(menuTargets[index]);});
document.querySelectorAll('[button-focus]').forEach(button=>{button.onclick=actions[button.getAttribute('button-focus')]||about;});
$('#demo-close').onclick=closeDialog;dialog.addEventListener('cancel',e=>{e.preventDefault();closeDialog();});dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog();}});
$('#demo-back').onclick=()=>{if(historyStack.length)showSection(historyStack.pop(),false);};$('#demo-home').onclick=()=>{historyStack.length=0;showSection('default_view',false);};$('#demo-help').onclick=about;$('#demo-start').onclick=()=>showSection('entertainment_menu');
document.addEventListener('keydown',event=>{if(!['ArrowDown','ArrowUp','ArrowLeft','ArrowRight'].includes(event.key)||['INPUT','SELECT','TEXTAREA'].includes(event.target.tagName))return;const root=dialog.open?dialog:document;const buttons=[...root.querySelectorAll('button,a[href]')].filter(b=>b.getClientRects().length&&!b.disabled);const index=buttons.indexOf(document.activeElement);if(index<0||!buttons.length)return;event.preventDefault();const offset=['ArrowDown','ArrowRight'].includes(event.key)?1:-1;buttons[(index+offset+buttons.length)%buttons.length].focus();});
function updateHeader(){const now=new Date();$('.time').textContent=new Intl.DateTimeFormat('en-AU',{timeZone:'Australia/Melbourne',weekday:'short',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}).format(now);}
updateHeader();setInterval(updateHeader,30000);showSection('default_view',false);
